### ISSUE TITLE
Point System Fixes and Additions Checklist

### ISSUE THREAD

**Issue by devsavage** [savageboy74/savagebot#6]
- [x] Rework how many points users get for chat messages and maybe don't give a user points for certain commands.

- [ ] If a user were to spam, they get A LOT of points plus more if they are verified on my site. LIMIT points.

- [ ] When giving points to a user for joining we should check the last they joined so they don't leave and rejoin for more points...

- [x] When a user queries for their points with the !points command, they get more points, I thought this was fixed but I guess not?

- [ ] Add users to a queue after chatting to slow down the rate in which they receive points. Maybe 10 seconds?
